trigger: none

# Pull request triggers for Azure DevOps repos are configured via branch policies.
# Go to: Repos > Branches > Branch Policies > Build Validation to add this pipeline.

pool:
  name: 'mdp-linux-mcaps'

variables:
- group: 'GitHub-Copilot'

resources:
  containers:
    # GitHub Copilot CLI service container
    - container: copilot_cli
      image: '$(ACR_NAME).azurecr.io/github-copilot/cli:latest'
      ports:
        - 4321:4321
      options: '--headless --port 4321'

services:
  copilot_cli: copilot_cli

steps:
- task: Docker@2
  displayName: 'Run Pull Request Container'
  inputs:
    containerRegistry: $(ACR_SERVICECONNECTION_NAME)
    repository: 'ado'
    command: 'run'
    arguments: >-
      --name pr-agent-container
      -e COPILOT_GITHUB_TOKEN=$(COPILOT_GITHUB_TOKEN)
      $(ACR_NAME).azurecr.io/ado/PullRequestAgent:latest
      --ado-token $(System.AccessToken)
      --pull-request-id $(System.PullRequest.PullRequestId)
      --organization-name $(ADO_ORGANIZATION_NAME)
      --project-name $(System.TeamProject)
      --repository-name $(Build.Repository.Name)
      --save-output
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- script: |
    docker cp pr-agent-container:/app/pull_request_$(System.PullRequest.PullRequestId)_review.md $(Build.ArtifactStagingDirectory)/
  displayName: 'Extract review file from container'

- powershell: |
    $reviewFile = "$(Build.ArtifactStagingDirectory)/pull_request_$(System.PullRequest.PullRequestId)_review.md"
    $content = Get-Content -Path $reviewFile -Raw
    $body = @{
      comments = @(@{ parentCommentId = 0; content = $content; commentType = 1 })
      status = 1
    } | ConvertTo-Json -Depth 3
    $uri = "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=7.1"
    $headers = @{
      Authorization  = "Bearer $(System.AccessToken)"
      'Content-Type' = "application/json"
    }
    Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body ([System.Text.Encoding]::UTF8.GetBytes($body)) -ContentType "application/json"
  displayName: 'Post review as PR comment'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    
- task: PublishPipelineArtifact@1
  displayName: 'Publish review artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'PullRequestReview'
