trigger: none

# Pull request triggers for Azure DevOps repos are configured via branch policies.
# Go to: Repos > Branches > Branch Policies > Build Validation to add this pipeline.

pool:
  name: '<value>'

variables:
- group: 'GitHub-Copilot'

steps:
# Start the GitHub Copilot CLI as a background service container
- task: Docker@2
  displayName: 'Start Copilot CLI Service'
  inputs:
    containerRegistry: $(DOCKER_SERVICECONNECTION_NAME)
    command: 'run'
    arguments: >-
      --name copilot-cli
      -e COPILOT_GITHUB_TOKEN=$(COPILOT_GITHUB_TOKEN)
      -d
      -p 4321:4321
      -v $(Build.ArtifactStagingDirectory)/copilot:/work/copilot
      -v $(Build.SourcesDirectory):/sources
      $(ACR_NAME).azurecr.io/github-copilot/cli:latest
      --headless --port 4321 --log-level info --log-dir /work/copilot

- task: Docker@2
  displayName: 'Run Pull Request Container'
  inputs:
    containerRegistry: $(DOCKER_SERVICECONNECTION_NAME)
    repository: 'ado'
    command: 'run'
    arguments: >-
      --name pr-agent-container
      --network container:copilot-cli
      $(ACR_NAME).azurecr.io/ado/pullrequestagent:latest
      --ado-token $(System.AccessToken)
      --pull-request-id $(System.PullRequest.PullRequestId)
      --organization-name $(ADO_ORGANIZATION_NAME)
      --project-name $(System.TeamProject)
      --repository-name $(Build.Repository.Name)
      --model $(MODEL_NAME)
      --output-directory /output
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- script: |
    docker cp pr-agent-container:/output/. $(Build.ArtifactStagingDirectory)/output/
  displayName: 'Copy assistant output from container'

- task: PublishPipelineArtifact@1
  displayName: 'Publish review artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'PullRequestReview'

- powershell: |
    $reviewFile = "$(Build.ArtifactStagingDirectory)/copilot/copilot-review.md"
    $content = Get-Content -Path $reviewFile -Raw
    $body = @{
      comments = @(@{ parentCommentId = 0; content = $content; commentType = 1 })
      status = 1
    } | ConvertTo-Json -Depth 3
    $uri = "$(System.CollectionUri)$(System.TeamProject)/_apis/git/repositories/$(Build.Repository.Name)/pullRequests/$(System.PullRequest.PullRequestId)/threads?api-version=7.1"
    $headers = @{
      Authorization  = "Bearer $(System.AccessToken)"
      'Content-Type' = "application/json"
    }
    Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body ([System.Text.Encoding]::UTF8.GetBytes($body)) -ContentType "application/json"
  displayName: 'Post review as PR comment'
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)

- script: |
    docker stop copilot-cli || true
    docker rm copilot-cli || true
  displayName: 'Cleanup Copilot CLI container'
  condition: always()