trigger: none

# schedule:
#   - cron: "0 6 * * *"
#     displayName: "Daily 06:00 UTC build"
#     branches:
#       include:
#         - main
#     always: true

pool:
  # use the one that fits your organization needs
  #vmImage: ubuntu-latest
  #name: '<value>'

variables:
  - name: ACR_LOGIN_SERVER
    value: $(ACR_LOGIN_SERVER)
  - name: ACR_NAME
    value: $(ACR_NAME)
  - name: IMAGE_NAME
    value: 'github-copilot/cli'

steps:
  - checkout: self

  - task: Bash@3
    name: copilotVersion
    displayName: 'Fetch latest GitHub Copilot CLI release tag'
    inputs:
      targetType: inline
      script: |
        RESPONSE=$(curl -sf https://api.github.com/repos/github/copilot-cli/releases/latest)

        if [ $? -ne 0 ]; then
          echo "##vso[task.logissue type=error]Failed to fetch release from GitHub API"
          exit 1
        fi

        LATEST_TAG=$(echo "$RESPONSE" | jq -r '.tag_name')

        if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" = "null" ]; then
          echo "##vso[task.logissue type=error]Failed to parse tag_name from API response"
          exit 1
        fi

        # Strip leading 'v' prefix if present (e.g. v0.0.409 -> 0.0.409)
        VERSION="${LATEST_TAG#v}"

        echo "##vso[task.setvariable variable=tag;isOutput=true]${LATEST_TAG}"
        echo "##vso[task.setvariable variable=version;isOutput=true]${VERSION}"
        echo "Detected latest Copilot CLI release: ${LATEST_TAG} (version: ${VERSION})"

  - task: Docker@2
    displayName: 'Docker login to ACR'
    inputs:
      command: login
      containerRegistry: $(DOCKER_SERVICECONNECTION_NAME)

  - task: AzureCLI@2
    name: versionCheck
    displayName: 'Check if version already exists in ACR'
    inputs:
      azureSubscription: $(ACR_SERVICECONNECTION_NAME)
      scriptType: bash
      scriptLocation: inlineScript
      inlineScript: |
        VERSION="$(copilotVersion.version)"
        EXISTING_TAGS=$(az acr repository show-tags \
          --name "$(ACR_NAME)" \
          --repository "$(IMAGE_NAME)" \
          --output tsv 2>/dev/null || true)

        if echo "$EXISTING_TAGS" | grep -qx "$VERSION"; then
          echo "Version ${VERSION} already exists in ACR. Skipping build and push."
          echo "##vso[task.setvariable variable=exists;isOutput=true]true"
        else
          echo "Version ${VERSION} not found in ACR. Proceeding with build and push."
          echo "##vso[task.setvariable variable=exists;isOutput=true]false"
        fi

  - task: Docker@2
    displayName: 'Build and push Docker image'
    condition: ne(variables['versionCheck.exists'], 'true')
    inputs:
      command: buildAndPush
      containerRegistry: $(DOCKER_SERVICECONNECTION_NAME)
      repository: $(ACR_LOGIN_SERVER)/$(IMAGE_NAME)
      dockerfile: src/GitHubCopilotCLIDocker/Dockerfile
      buildContext: src/GitHubCopilotCLIDocker
      tags: |
        latest
        $(copilotVersion.version)
        $(Build.SourceVersion)
      arguments: --build-arg CACHE_BUSTER=$(Build.BuildId)
